git:
  submodules: false
language: generic
matrix:
    include:
        - os: linux
          sudo: required
          dist: xenial
          env: LOAD_INTO_KICAD=true
          before_install:
            - sudo add-apt-repository ppa:js-reynaud/kicad-dev-nightly -y
            - sudo add-apt-repository ppa:js-reynaud/kicad-5 -y
            - sudo apt-get update -q
            - sudo apt-get install --no-install-recommends kicad kicad-nightly -y
        - os: osx
          env: LOAD_INTO_KICAD=false
script:
  - while [ 1 ]; do echo "keeping travis alive"; sleep 540; done &
  - ./init
  - ./update
  - if $LOAD_INTO_KICAD; then PYTHONPATH=/usr/lib/kicad-nightly/lib/python2.7/dist-packages python2 load_all.py; fi
